// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIasQ3XJT79eDtBgUHG-Y8KeqMd_bs1Kk',
    appId: '1:70735585333:web:22eaf1dc915c698d05117c',
    messagingSenderId: '70735585333',
    projectId: 'genshin-data-ga4',
    authDomain: 'genshin-data-ga4.firebaseapp.com',
    storageBucket: 'genshin-data-ga4.appspot.com',
    measurementId: 'G-HKGPDLPQ1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZJklKfED3FYJcIFU-nOSo0TYly50xO6s',
    appId: '1:70735585333:android:6a4c5500bc010c6105117c',
    messagingSenderId: '70735585333',
    projectId: 'genshin-data-ga4',
    storageBucket: 'genshin-data-ga4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa76J02Sb40IbQ3uD_wPJI1DpBBky-rpg',
    appId: '1:70735585333:ios:32a817a68821f74005117c',
    messagingSenderId: '70735585333',
    projectId: 'genshin-data-ga4',
    storageBucket: 'genshin-data-ga4.appspot.com',
    iosBundleId: 'com.example.genshinApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa76J02Sb40IbQ3uD_wPJI1DpBBky-rpg',
    appId: '1:70735585333:ios:32a817a68821f74005117c',
    messagingSenderId: '70735585333',
    projectId: 'genshin-data-ga4',
    storageBucket: 'genshin-data-ga4.appspot.com',
    iosBundleId: 'com.example.genshinApp',
  );
}
